logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/webapp_logs/webappLog.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: timestamp
      time_format: "%Y-%m-%dT%H:%M:%S.%LZ"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.level
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor, move_severity]
